name: Release-sublime-package

env:
  PACKAGE_NAME: "Cps Run Commands.sublime-package"

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: msg
      run: echo "start package ${{env.PACKAGE_NAME}}"

    - name: Checkout
      uses: actions/checkout@v3

    - name: Zip The File
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: ${{env.PACKAGE_NAME}}
        exclusions: '*.git* /*node_modules/* .editorconfig .github/ .gitignore/ .git/'

    - name: ls
      run: ls -al

    - name: Upload the gihub Release
      uses: softprops/action-gh-release@v1
      with:
        token: ${{ secrets.TOKEN }}
        fles: |
          ${{env.PACKAGE_NAME}}
